---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  selector:
    matchLabels:
      app: example-backend
  template:
    metadata:
      labels:
        app: example-backend
    spec:
      containers:
      - name: example
        image: localhost:32000/example_server:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: example-backend-service
spec:
  type: ClusterIP
  selector:
    app: example-backend
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-backend-ingress
spec:
  rules:
    - host: example-backend.local
      http:
        paths:
          - backend:
              service:
                name: example-backend-service
                port:
                  name: http
            pathType: Prefix
            path: /