apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: compose-to-skaffold
build:
  artifacts:
  - image: localhost:32000/example_server
    context: go
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/*'
          dest: /app/
          strip: 'src/'
      hooks:
        after:
          - container:
              command: ["go", "build", "-o", "./example_server", "main.go"]
          - container:
              command: ["supervisorctl", "restart", "all"]
deploy:
  kubectl:
    manifests:
    - manifest.yaml
